### ISSUE TITLE
AaaLib still has no tests

### ISSUE THREAD

**Issue by rdeago** [Tenacom/AaaLib#10]
### Affected version(s)

1.0.60

### Is this a regression?

NO - This bug also affected the previous version

### Context

There are no tests in this repository.

Also, quite obviously, no coverage reports.

### Expected behavior

PR checks should include running tests.

The release workflow should, too.

### Actual behavior

`dotnet test` is executed in the above-mentioned workflows, but it does nothing, as there are no tests.

(I'm getting boring, I know.)

### How to reproduce

n/a

### Configuration

n/a

### Other information

AaaLib being an incubator for Tenacom's procedures and internal standards, it's not only a matter of writing tests. Which unit testing library do we use? Do we also use some helper library, e.g. FluentAssertions? Etc.

It's important to have a standard, so people can "jump" between projects and feel at home.

**Comment by ric15ni** [comment]
I'm currently researching libraries and tools we can use. I'm going to open a discussion with the results, as it seems a better approach than stuffing them in an issue.

**Comment by ric15ni** [comment]
Find the discussion here: #11
