### ISSUE TITLE
Missing documentation pages

### ISSUE THREAD

**Issue by ric15ni** [Tenacom/AaaLib#5]
### Affected version(s)

1.0.1-preview

### Regression?

NO - This is a new bug

### Context

Static pages in docs still have their default contents from DocFx template.

### Expected behavior

The following files should contain something that at least makes _some_ sense:

- `docs/index.md`
- `docs/apidoc/index.md`
- `docs/articles/intro.md`

### Actual behavior

The above-mentioned files still have their default contents. 🙈 

### How to reproduce

Build and serve documentation:
```shell
dotnet cake docs.cake --target All
```

Then open a browser on `localhost:8080`.

### Configuration

Configuration is not important for this issue.

### Other information

Writing this was a sub-optimal experience. We need a template for documentation-related issues.

**Comment by rdeago** [comment]
Good catch @ric15ni, a PR would be appreciated.

**Comment by rdeago** [comment]
> Writing this was a sub-optimal experience. We need a template for documentation-related issues.

Please open an issue about that.
